version: '3.4'

services:
  mongodb:
    image: mongo:3.2.4
    container_name: 'mongodb'
    ports:
      - 27017:27017
    command: --smallfiles
  touristspot:
    image: touristspot
    build: .
    ports:
      - 8080:8080
    links: -mongodb
