spring:
  datasource.driverClassName: MongoDB
  data:
    mongodb:
      database: touristspot
      uri: mongodb://mongodb/demorest
      host: mongodb
      port: 27017
---
# Development configurations
spring:
  profiles:
    - development
  data:
    mongodb:
      database: touristspot

---
# Testing configurations
spring:
  profiles:
    - test
  data:
    mongodb:
      database: test
