#Swagger 2
host.full.dns.auth.link: http://localhost:8080
app:
  client:
    id: touristspot
    secret: 123

---
# Production configurations
host.full.dns.auth.link: https://touristspotrest.herokuapp.com/
spring:
  profiles:
    - production
  data:
    mongodb:
      database: touristspot

---
# Development configurations

host.full.dns.auth.link: http://localhost:8080

spring:
  profiles:
    - development
  data:
    mongodb:
      database: touristspot

---
# Testing configurations
spring:
  profiles:
    - test
  data:
    mongodb:
      database: test

---
# Production configurations
host.full.dns.auth.link: https://touristspotrest.herokuapp.com/
spring:
  profiles:
    - docker
  data:
    mongodb:
      database: touristspot
      host: mongo
      port: 27017



