spring:

  thymeleaf:
    cache: false

  data:
    mongodb:
      database: touristspot

---

# Development configurations
spring:
  profiles:
    - development
  data:
    mongodb:
      database: touristspot

---

# Testing configurations
spring:
  profiles:
    - test
  data:
    mongodb:
      database: test