#Swagger 2
host.full.dns.auth.link: http://localhost:8080
app:
  client:
    id: touristspot
    secret: 123

---
host.full.dns.auth.link: https://touristspotrest.herokuapp.com/
spring:
  profiles:
    - production
  data:
    mongodb:
      database: touristspot
      uri: mongodb+srv://omnistackjs:DKLT2Jzbcu28Nd4@cluster0-othjt.mongodb.net/test?retryWrites=true&w=majority

---
# Development configurations

host.full.dns.auth.link: http://localhost:8080

spring:
  profiles:
    - development
  data:
    mongodb:
      database: touristspot

---
# Testing configurations
spring:
  profiles:
    - test
  data:
    mongodb:
      database: test
